### ISSUE TITLE
Sizeof of buffer or pointer?

### ISSUE THREAD

**Issue by miky2k** [LowPowerLab/SI7021#1]
void SI7021::_command(byte \* cmd, byte \* buf ) {
    _writeReg(cmd, sizeof cmd);
    _readReg(buf, sizeof buf);
}

I does not understand the sizeof  of buf , it seems that you ask size of a pointer and not buffer length,
is this correct ?
i think that the correct function should be _command(byte \* cmd,int cmdlen, byte \* buf ,int buflen);

**Comment by LowPowerLab** [comment]
This is now fixed with [this update](https://github.com/LowPowerLab/SI7021/commit/2de083b8cbb9c0e8c7bf8f21274915719e468bf8).
