### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [LowPowerLab/SI7021#12]
In the file "SI7021.cpp" in the function "readReg()" a call to Wire.requestFrom() is made and after that while-loop to wait for something. That while loop can be removed, there is nothing to wait for.

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library.
When Wire.available() is called directly after Wire.requestFrom(), it returns the number of bytes in that buffer and is the same as the number of requested bytes if the I2C transaction was successful. When there was a I2C bus error, the Wire.avaible() probably returns zero.

**Comment by LowPowerLab** [comment]
You're right, thanks, do you want to submit a PR?

**Comment by LowPowerLab** [comment]
NVM, merged [here](https://github.com/LowPowerLab/SI7021/commit/a8e617ee2880a2a894730931160ae756dc872723).
