### ISSUE TITLE
sensorExists?

### ISSUE THREAD

**Issue by Bierchermuesli** [LowPowerLab/SI7021#13]
Hi
first of all - thanks for this slim and compact library. 

I saw there is a `sensorExists`  option. I din't found much in the source code, is this option implemented? 

At the moment I running into issues if the sensor is not available (...anymore) - or do somebody know other ways to stop a blocking state like this?

thanks in advance

**Comment by LowPowerLab** [comment]
The `sensorExists` is set in [SI7021.begin() here.](https://github.com/LowPowerLab/SI7021/blob/master/SI7021.cpp#L43)
