### ISSUE TITLE
Does setHeater reset precision?

### ISSUE THREAD

**Issue by jamesmyatt** [LowPowerLab/SI7021#15]
Am I right in saying that `setHeater` resets the precision to the default?
https://github.com/LowPowerLab/SI7021/blob/master/SI7021.cpp#L156

**Comment by LowPowerLab** [comment]
Please reference datasheet of your findings and provide details of a bug before you open an issue.

**Comment by jamesmyatt** [comment]
It looks like the setHeader method sets the whole user register, which includes the resolution settings. Compare with the setResolution method.

I'm just saying based on the source code. If it doesn't then there needs to be a comment to clarify.

**Comment by LowPowerLab** [comment]
Depending if heater parameter it sets it to (see [DSheet](https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf)):

- 0x3A (0011_1010 - POR default) for OFF
- 0x3E (0011_1110) for ON

So yes, it would set the resolution bits to 00 in both cases - which is maximum resolution (12bit RH and 14bit Temp)

Is this really an issue?

**Comment by jamesmyatt** [comment]
Not for me, but it might be for someone. Might be best to at least mention it in comments.

**Comment by LowPowerLab** [comment]
Ok i will add a comment then.
Thanks!
