### ISSUE TITLE
Wire.Begin on esp8266 misses the arguments

### ISSUE THREAD

**Issue by TheDonDan** [LowPowerLab/SI7021#4]
Hi Felix Rusu,

Realy nice library.
I was trying to use an SI7021 sensor with an esp8266, and it first didn't work. It did not initialize the sensor... I noticed that the reason is that you forgot to pass the SDA,SCL arguments to the Wire.begin function.
An easy work around is to define again the Wire.Begin(SDA,SCL) function in the sketch.

Cheears

DonDan

**Comment by LowPowerLab** [comment]
Hi DonDan,
Thanks for the suggestion.
But I cannot find a definition for Wire.begin(..)  that takes 2 arguments (for scl,sda).
Which version of Arduino are you using?

**Comment by TheDonDan** [comment]
Hi Felix

the Wire.begin() function does only take the sda,scl arguments if you compile it for the esp8266 board, because there you can use any gpio combi for the i2c and hence you must define it. The regular Arduinos have the SDA and SCL predefined, that why the Wire.begin() doent take any arguments there.

In the file SI7021.cpp it must be:

#if defined(ARDUINO_ARCH_ESP8266)

bool SI7021::begin(int SDA, int SCL) {

    Wire.begin(SDA,SCL);

#else

Thank you for your attention,

Cheers

Dondan

**Comment by LowPowerLab** [comment]
Thanks, fixed in this commit: https://github.com/LowPowerLab/SI7021/commit/430595cbf6d34e5dfec8144c47dd9b36c7e7aa60
