### ISSUE TITLE
getSerialBytes only returns 12 bytes when it should return 14

### ISSUE THREAD

**Issue by jhoward88** [LowPowerLab/SI7021#6]
The datasheet for the Si7021 shows that when the serial number is requested via software,  it gives the data back in two chunks, the first is 8 bytes long and the second is 6 bytes long. Some of the bytes are used for CRC (cyclic redundancy check).
The total actual bytes of serial number data amounts to 8 particular bytes out of that 14.  

The problem is that the getSerialBytes(byte \* buf) function only gives back 12 bytes instead of the 14 it should.  Unfortunately,  the 12 bytes miss one piece of the actual serial number itself.  When I hooked up, in succession, the seven Si7021's that I have at the house,  two of them reported the same serial number!

For my own use I edited the Si7021 library and added a function that returns just the 8 bytes that are the actual serial number we need. After I added the modified library to my project everything works and the serial numbers are unique.

Here is my function (note that it ignores the CRC bytes):

The datasheet for the Si7021 shows that when the serial number is requested via software,  it gives the data back in two chunks, the first is 8 bytes long and the second is 6 bytes long. Some of the bytes are used for CRC (cyclic redundancy check).
The total actual bytes of serial number data amounts to 8 particular bytes out of that 14.  

The problem is that the getSerialBytes(byte \* buf) function only gives back 12 bytes instead of the 14 it should.  Unfortunately,  the 12 bytes miss one piece of the actual serial number itself.  When I hooked up, in succession, the seven Si7021's that I have at the house,  two of them reported the same serial number!

For my own use I edited the Si7021 library and added a function that returns just the 8 bytes that are the actual serial number we need. After I added the modified library to my project everything works and the serial numbers are unique.

Here is my function (note that it ignores the CRC bytes):

int SI7021::get8SerialBytes(byte \* buf) {
    byte serial[8];
    _writeReg(SERIAL1_READ, sizeof SERIAL1_READ);
    _readReg(serial, 8);
    buf[0] = serial[0];  //These are the bytes 
    buf[1] = serial[2];  //from the datasheet
    buf[2] = serial[4];  //that are the
    buf[3] = serial[6];  //actual serial  
    _writeReg(SERIAL2_READ, sizeof SERIAL2_READ);
    _readReg(serial, 6);
    buf[4] = serial[0];  //Again these are the 
    buf[5] = serial[1];  //SN bytes
    buf[6] = serial[3];  //
    buf[7] = serial[4];  //
    return 1;
}

**Comment by LowPowerLab** [comment]
Thanks for the detailed explanation, certainly something I will look to merge.
Although the next rev of the WShield will come with the BME280.

**Comment by LowPowerLab** [comment]
Fixed the original getSerialBytes() function.
Many thanks!
